### ISSUE TITLE
code review | välipalautus 2

### ISSUE THREAD

**Issue by kriskrok** [nameisxi/resume-review-service#1]
Muutamia huomioita. Kurssi ja sitä myöten myös sovellus on vasta varhaisessa vaiheessa joten luethan näitä 'voisi toteuttaa tulevaisuudessa' -lasit päässä:

- Kooltaan isommankin (4,5 Mb) pdf:n lähetys sovellukseen onnistui. Tähän liittyen sovellukseen voisi harkita tulevaisuudessa toteuttettavaksi jonkinmoisen tiedostokoon ylärajan sekä visuaalisen indikaattorin josta käyttäjä tietää lähetyksen lähteneen onnistuneesti käyntiin/olevan vielä kesken.
- Luotaessa uutta käyttäjätiliä spostiosoitteella joka on jo käytössä, tulee käyttäjä ohjatuksi näkymään jossa toki tapahtuneesta erheestä ilmoitetaan, mutta navigointimahdollisuus sivulta eteenpäin/taaksepäin uupuu. Tapahtuneesta virheestä voisi viestiä käyttäjälle myös suoraan "signup"-sivulla. Näini käyttäjää ei tarvitse ohjata erilliseen näkymään pois käyttäjätunnuksen luonnin parista. Lisäksi vaatimuksen uniikista spostiosoitteesta voisi lisäksi lisätä myös suoraan kantaan käyttämällä unique rajoitinta users-taulun email-sarakkeessa.
- Sovelluksen testikäyttöä ja tutustumista helpottamaan voisi luoda README:hin lisättävät testikäyttäjätunnukset. Nykyisellään "Reviewer"-roolissa toimimisesta pääsee hakemaan tuntumaa ainoastaan kurkkimalla repositorioon '[generate-test-data-script.sql](https://github.com/nameisxi/resume-review-service/blob/master/generate-test-data-script.sql)' tiedostosta kannan luonnin yhteydessä luotava tuomo-testikäyttäjän tunnukset.
- Tietokantakuvaus on järkevä, lisäksi koodin ja templaten jäsentely on selkeää. [App.py](https://github.com/nameisxi/resume-review-service/blob/master/app.py) tiedostosta voisi eriyttää omaan tiedostoonsa käyttäjien tunnuksen luontiin ja validointiin liittyvät toiminnallisuudet.

Tsemppiä loppukurssille ja hyvää kevään odotusta!

**Comment by nameisxi** [comment]
Kiitos palautteesta, se tulee hyvään käyttöön. Hyvät kevään odotukset myös sinne! 😎

**Comment by Jouchef** [comment]
Moikka! 

- Ensivaikutelma sovelluksesta on todella hyvä. Ulkonäkö on moderni ja sivusto toimii nopeasti. Lisäksi toiminnot ovat selkeästi aseteltu ja toimivat, kuin käyttäjä odottaisikin. 
- Sivusto vaikuttaa toimivan hyvin puhelimella, sekä tietokoneella.
- CV:tä lisätessä tiedostoselain näytti vain pdf:iä. Hyvä! 
- Onko tiedostokokoa rajoitettu?
-  Kun tiedostoa latasi, voisi sivusto ilmoittaa latauksen onnistuneen. 
- Mikäli ladataan samannimistä tiedostoa, kun servulla jo on, voisiko näitä jotenkin "niputtaa" yhteen? 
- CV:tä voisi myös näyttää sivulla vain rajallisen määrän?
- Entäpä jos käyttäjä voisi filtteröidä näkyviin CV:t joihin hän on saanut kommentteja?
- Resumes-sivulla "Submitted at:" ajankohdan voisi muotoilla kivemman näköiseksi. Käyttäjä ei tee koko rimpsun tiedolla. 

- Mitä tapahtuu mikäli joku CV:n tarkastajista poistaa tilinsä? Määritetäänkö hänen tarkastettaville CV:ille uudet tarkastajat? 

Tietokanta vaikutti fiksusti tehdyltä ja se ei esim salli useita samannimisiä käyttäjiä. 
Rekisteröitymis-sivulta **pitäisi** olla linkki takaisin etusivulle.


Hyvältä vaikuttaa! Laitoin tähän paljon kysymyksiä ajatuksien ja ideoiden synnyttämiseksi.
