### ISSUE TITLE
Tsoha - code review 2

### ISSUE THREAD

**Issue by Jouchef** [nameisxi/resume-review-service#2]
Moikka!

Ensivaikutelma sovelluksesta on todella hyvä. Ulkonäkö on moderni ja sivusto toimii nopeasti. Lisäksi toiminnot ovat selkeästi aseteltu ja toimivat, kuin käyttäjä odottaisikin.

Sivusto vaikuttaa toimivan hyvin puhelimella, sekä tietokoneella.

CV:tä lisätessä tiedostoselain näytti vain pdf:iä. Hyvä!

Onko tiedostokokoa rajoitettu?

Kun tiedostoa latasi, voisi sivusto ilmoittaa latauksen onnistuneen.

Mikäli ladataan samannimistä tiedostoa, kun servulla jo on, voisiko näitä jotenkin "niputtaa" yhteen?

CV:tä voisi myös näyttää sivulla vain rajallisen määrän?

Entäpä jos käyttäjä voisi filtteröidä näkyviin CV:t joihin hän on saanut kommentteja?

Resumes-sivulla "Submitted at:" ajankohdan voisi muotoilla kivemman näköiseksi. Käyttäjä ei tee koko rimpsun tiedolla.

Mitä tapahtuu mikäli joku CV:n tarkastajista poistaa tilinsä? Määritetäänkö hänen tarkastettaville CV:ille uudet tarkastajat?

Tietokanta vaikutti fiksusti tehdyltä ja se ei esim salli useita samannimisiä käyttäjiä.
Rekisteröitymis-sivulta pitäisi olla linkki takaisin etusivulle.

Hyvältä vaikuttaa! Laitoin tähän paljon kysymyksiä ajatuksien ja ideoiden synnyttämiseksi.

**Comment by nameisxi** [comment]
Moikka! 

Pahoittelut viivästyneestä vastauksesta. Kiitos palautteesta ja ideoista! 

Olen nyt saanut hiottua kaiken muun paitsi CV "niputuksen". Jouduin myös tekemään pienen muutoksen users tauluun niin, että duplikaattikäyttäjiä voi olla, mutta vain yksi niistä on aktiivinen. Näin käyttäjä voi poistaa ja uudelleenluoda tilinsä.

Mukavaa kevään odotusta ja loppukurssia!
